---
# Title
TITLE-ACIDUI: "§l§9⚫§a Hệ Thống Cúp §9⚫"
#Exit
BTN-EXT: "§l§e•§c Thoát §e•"
#
#GiveCup BUTTON
BTN-CRT: "§l§e•§b Mua CÚP §e•"
#
#TOP Cup BUTTON
BTN-TP: "§l§e•§b TOP Cúp §e•"
#
#==========================================
...