---
marker:
  1: 1000
  2: 1100
  3: 1200
  4: 1300
  5: 1400
  6: 1500
  7: 1600
  8: 1700
  9: 1800
  10: 1900
  11: 2000
  12: 2100
  13: 2200
  14: 2300
  15: 2500
  16: 2600
  17: 2700
  18: 2800
  19: 2950
  30: 3100
  31: 3200
  32: 3300
  33: 3300
  34: 3300
  35: 3300
  36: 3300
  37: 3400
  38: 3400
  39: 3500
  40: 3500
  41: 3600
  42: 3600
  43: 3700
  44: 3800
  45: 3900
  46: 4000
  47: 4100
  48: 4200
  49: 4300
  50: 4400
  51: 4500
  52: 4600
  53: 4700
  54: 4800
  55: 4900
  60: 5000
  61: 5100
  62: 5200
  63: 5300
  64: 5500
  66: 5600
  67: 5700
  68: 5800
  69: 5900
  70: 7100
  71: 7200
  73: 7400
  74: 7600
  75: 7800
  76: 8000
  77: 8200
  78: 8400
  79: 8600
  80: 8800
  81: 9000
  82: 9200
  83: 9400
  84: 9600
  85: 9800
  86: 10000
database:
  LocDz2k9:
    block: 356
    level: 0
  LocProNe2k9:
    block: 1930
    level: 10
  DetestedRobin47:
    block: 0
    level: 0
  YTBJero:
    block: 57
    level: 0
  HeavPlaysMC:
    block: 0
    level: 0
  MGCPro2982:
    block: 912
    level: 0
  heropcgaming65:
    block: 0
    level: 0
  OffHau Gaming:
    block: 6
    level: 0
  KingknightVN:
    block: 89
    level: 0
  FBINockNock:
    block: 1
    level: 0
  Anhcanhetok:
    block: 118
    level: 0
  ConstantChip316:
    block: 0
    level: 0
  Kiet_fb_3219:
    block: 0
    level: 0
  Proplayer8949:
    block: 28
    level: 0
  NhiCute2k41233:
    block: 0
    level: 0
  MCDontDoThat:
    block: 0
    level: 0
  haongu1592k8:
    block: 5
    level: 0
  ItzMatsterZz:
    block: 180
    level: 0
  Danh205:
    block: 167
    level: 0
  OffNhicute:
    block: 0
    level: 0
  KakaShiReal123:
    block: 240
    level: 0
  Khanh392007:
    block: 7
    level: 0
  NuiNoPro:
    block: 1884
    level: 9
  WeeklyTea628799:
    block: 563
    level: 0
  NamYTGaming:
    block: 0
    level: 0
  BaByTUFFGAME:
    block: 26
    level: 0
  Top1gazrel:
    block: 20
    level: 0
  HuyVN7440:
    block: 0
    level: 0
  Yasuo0011:
    block: 0
    level: 0
  tapL050:
    block: 1
    level: 0
  khoastr:
    block: 12067
    level: 19
  ThaiNoPro6215:
    block: 7234
    level: 19
  WindedBark25881:
    block: 0
    level: 0
  Dneeeeee:
    block: 1
    level: 0
  NhanAZ:
    block: 0
    level: 0
  Tuananh24608:
    block: 10
    level: 0
  LearnedLotus766:
    block: 8789
    level: 19
  VanhLXYTB:
    block: 60
    level: 0
  s3thuandz:
    block: 0
    level: 0
  OctalMoney88347:
    block: 10
    level: 0
  MilliannaB:
    block: 5666
    level: 19
  Kiendz452008:
    block: 1421
    level: 5
  ThanhMcpeVn:
    block: 0
    level: 0
  FairScorpion486:
    block: 0
    level: 0
  EerySphere38042:
    block: 0
    level: 0
  DamChatDanChoi3:
    block: 0
    level: 0
  DanhBui8767:
    block: 0
    level: 0
  NovaStark1245:
    block: 7749
    level: 19
  VietNgu1280:
    block: 780
    level: 0
  VN HIEU1230:
    block: 1290
    level: 3
  DaiCaQuanXi:
    block: 0
    level: 0
  DaiCaDaiGa:
    block: 0
    level: 0
  Bangn090kna:
    block: 3142
    level: 19
  TaLaSieuNhan:
    block: 0
    level: 0
...
