# Config file for VoteReward by LDX.
#
# Official VoteReward Server List Directory:
# http://votereward.mcpe.me/?p=lists
#
# Config Variables:
#   {USERNAME} ... The username of the player who voted. ....... Commands and message.
#   {NICKNAME} ... The display name of the player who voted. ... Commands and message.
#   {X} .......... The X coordinate of the player. ............. Commands only.
#   {Y} .......... The Y coordinate of the player. ............. Commands only.
#   {Y1} ......... The Y coordinate of the player plus 1. ...... Commands only.
#   {Z} .......... The Z coordinate of the player. ............. Commands only.

# EssentialsPE style color codes can be used in the message and commands.

# Message to broadcast to the server when a player votes.
Message: "§l§6[§bиσναмιиє §aиєтωσяк§6]§f ↣§a Bạn đã vote cho máy chủ thành công và nhận phần thưởng!"

# List of items to give players when they vote. Format: ID:Damage:Amount
Items:

# List of commands to execute when a player votes.
Commands:
  - "givemoney {USERNAME} 5000"
  - "key Vote {USERNAME} 1"
