# SELLXP PLUGIN
# MADE BY: Rushil13579 | Rushil#2326

# FORMAPI SUPPORT [SET AS 'false' TO TURN OFF]
formapi-support: true

# THE TITLE OF THE FORM
form-title: "§l§9⚫§a Sell EXP §9⚫"

# THE CONTENT OF THE FORM
form-content: "§l§c↣ §aXu của bạn: §e".$money ."\n§l§c↣§a EXP của bạn: §e{xp}"

# THE NAME OF THE SLIDER [USE {xp-money-exchange-rate} TO GET THE VALUE IN 'amount-per-xp', i.e the exchange rate] [THE SELECTED AMOUNT OF XP WILL BE DISPLAYED AT THE END]
slider-name: "§l§e•§b Chọn số lượng EXP để bán\n§l§e•§a Giá bán EXP: §e{xp-money-exchange-rate}\n§l§c↣§a Chọn số lượng:"

# MESSAGE TO BE SENT IF THE PLAYER DOESNT HAVE ENOUGH XP!
not-enough-xp-msg: "§l§a[§bиσναмιиє §aиєтωσяк§a]§c Bạn không đủ EXP để bán"

# MESSAGE TO BE SENT IF THE ARGUMENT GIVEN BY THE PLAYER IS NOT A NUMBER!
non-numeric-argument: "§l§a[§bиσναмιиє §aиєтωσяк§a]§c Vui lòng không nhập số âm"

# MESSAGE TO BE SENT IF THE ARGUMENT GIVEN BY THE PLAYER IS NOT A INTEGER!
non-integer-given: "§l§a[§bиσναмιиє §aиєтωσяк§a]§c Vui lòng nhập số"

# MESSAGE TO BE SENT WHEN THE PLAYER SELLS XP [USE {xp} FOR AMOUNT OF XP SOLD AND USE {amount} FOR SELLING AMOUNT]
sellxp-msg: "§l§a[§bиσναмιиє §aиєтωσяк§a]§b Bạn đã bán §e{xp}§b EXP §e{amount}§b Xu"

# AMOUNT FOR EACH LEVEL OF XP! [XP-MONEY EXCHANGE RATE]
amount-per-xp: "500"

# IN-CASE OF ANY BUGS CONTACT THE OWNER AT THE ABOVE DETAILS!
