# ------------------------------------------------------
# ItemFrameProtector by WinterBuild7074 - Config
# ------------------------------------------------------

# In which worlds should Item Frames be protected?
ProtectedWorlds:
- "Spawn"
- "Shop"
- "PvP"