---
 
# If you want to add a paragraph then you only have to do 
# \n at the text then the text one goes down for example: Test\nTest = Test 
#                                                                     Test 
# So if you do this twice (\n\n), there's an empty line between the example Test
 
# Here you can switch the Description
Title: "§l§e•§b Luật Server §e•"
 
# Here you can switch the content
Content: "§l§o§9▃§b▃§a▃§e▃§6▃§c▃§4▃§2▃§d▃§f▃§7▃§8▃§5▃§1▃§0▃\n\n§l§c--> §aKhông sử dụng các phần mềm cheat Hack...\n§l§c--> §aKhông nói tục chửi thề hay gây War...\n§l§c--> §aCác trường hợp khác tuỳ mức độ và hành vi. Chúng tôi sẽ xử lí sau.\n§l§c--> §aKhông quảng cáo server, Spam Chat trên khung chat server.\n§l§c--> §aKhông tự ý giao dịch để tránh bị lừa đảo trong server.\n\n§l§o§9▃§b▃§a▃§e▃§6▃§c▃§4▃§2▃§d▃§f▃§7▃§8▃§5▃§1▃§0▃"
 
# Here you can switch the text for the Button
Button: "§l§e•§c Thoát §e•"
 
# Here you can add if the Player joins that then you have to set it to true
open_at_first_join: "true"
...
