#The Item ID for the SellWand, the default is a WOODEN_HOE
sell-wand-item-id: 369

#The Name to be given to the Sell Wand. Use & for colors.
sell-wand-item-name: "§l§cＳ§6Ｅ§eＬ§aＬ §bＷ§fＡ§dＮ§9Ｄ"

#The Item Lore(Description) for the Sell Wand. Use & for colors.
#Use the {USES} to display the remaining uses on the Sell Wand.
sell-wand-item-lore:
  - "§l§c⚫§a Bấm vào rương để bán."
  - "§l§c⚫§a Vật phẩm trị giá cao giữ gìn cẩn thận."
  - "§l§c⚫§a Vật phẩm khi bán đồ trong ruoeng sẻ nhận x2 tiền."
  - "§l§c⚫§a Số lần dùng: {USES}."

# The message to be sent when there are no items to Sell in the Chest
sell-wand-no-items-message: "§l§a[§bиσναмιиє §aиєтωσяк§a]§c Không có vật phẩm nào để bán trong rương."

# The message to be sent when items in the Chest are sold.
# Use {MONEY} to display the total revenue from selling the items in the chest.
sell-wand-use-message: "§l§a[§bиσναмιиє §aиєтωσяк§a]§b Đã bán vật phẩm trong rương thành công và số tiền bán§f: §e{MONEY} Xu"

# The message to be sent when a player uses a Sell Wand in a protected area.
# This is useful for servers like Skyblock to prevent players from selling chests not on their island
sell-wand-cant-use-here-message: "§l§a[§bиσναмιиє §aиєтωσяк§a]§c You cannot use Sell Wands here!"

# The message to send players who do not have permission to use Sell Wands
# The permission node is "sellwand.use"
sell-wand-no-permission-message: "§l§a[§bиσναмιиє §aиєтωσяк§a]§c Bạn không có quyền sử dụng Sell Wand"

# Setup item Sell Prices here
# Put all the ids and their price in here
# From SellAll by AndreasHGK
prices:
  1: 2
  4: 2
  15: 15
  14: 20
  21: 30
  129: 40
  56: 50
  265: 10
  266: 15
  264: 20
  351: 15
  388: 20
  263: 10
  16: 20
  73: 25
  331: 15
  41: 40
  57: 90
  133: 80
  173: 20
  42: 30
  21: 70
  22: 20
  152: 30